<a href="https://colab.research.google.com/github/Ravi-ranjan1801/Data-Warehousing-Mining-Lab/blob/main/DWM_Lab_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Lab - 05**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [2]:
data = {
    'Student ID': ['S01', 'S02', 'S03', 'S04', 'S05',
                   'S06', 'S07', 'S08', 'S09', 'S10'],

    'Age': [18, 19, 20, 21, 19, 22, 20, 23, 21, 24],

    'Attendance (%)': [65, 70, 75, 80, 85, 90, 72, 88, 95, 98],

    'Study Hours/Week': [5, 7, 8, 10, 12, 14, 6, 15, 18, 20],

    'Marks': [42, 48, 55, 60, 68, 75, 52, 82, 90, 96]
}

df = pd.DataFrame(data)

df

  Student ID  Age  Attendance (%)  Study Hours/Week  Marks
0        S01   18              65                 5     42
1        S02   19              70                 7     48
2        S03   20              75                 8     55
3        S04   21              80                10     60
4        S05   19              85                12     68
5        S06   22              90                14     75
6        S07   20              72                 6     52
7        S08   23              88                15     82
8        S09   21              95                18     90
9        S10   24              98                20     96

In [3]:
features = ['Age', 'Attendance (%)', 'Study Hours/Week', 'Marks']

X = df[features]

X

   Age  Attendance (%)  Study Hours/Week  Marks
0   18              65                 5     42
1   19              70                 7     48
2   20              75                 8     55
3   21              80                10     60
4   19              85                12     68
5   22              90                14     75
6   20              72                 6     52
7   23              88                15     82
8   21              95                18     90
9   24              98                20     96

In [4]:
statistics = pd.DataFrame({
    'Minimum': X.min(),
    'Maximum': X.max(),
    'Mean': X.mean(),
    'Median': X.median(),
    'Population Variance': X.var(ddof=0),
    'Population Std Dev': X.std(ddof=0)
})

statistics.round(3)

,Minimum,Maximum,Mean,Median,Population Variance,Population Std Dev
Age,18,24,20.7,20.5,3.21,1.792
Attendance (%),65,98,81.8,82.5,111.96,10.581
Study Hours/Week,5,20,11.5,11.0,24.05,4.904
Marks,42,96,66.8,64.0,306.36,17.503

### **Min-Max Normalization**

In [5]:
min_max = pd.DataFrame()

for column in features:
    min_val = X[column].min()
    max_val = X[column].max()

    min_max[column] = (
        (X[column] - min_val) /
        (max_val - min_val)
    )

min_max = pd.concat(
    [df[['Student ID']], min_max],
    axis=1
)

min_max.round(3)

  Student ID    Age  Attendance (%)  Study Hours/Week  Marks
0        S01  0.000           0.000             0.000  0.000
1        S02  0.167           0.152             0.133  0.111
2        S03  0.333           0.303             0.200  0.241
3        S04  0.500           0.455             0.333  0.333
4        S05  0.167           0.606             0.467  0.481
5        S06  0.667           0.758             0.600  0.611
6        S07  0.333           0.212             0.067  0.185
7        S08  0.833           0.697             0.667  0.741
8        S09  0.500           0.909             0.867  0.889
9        S10  1.000           1.000             1.000  1.000

### **Z-Score Normalization**

In [6]:
z_score = pd.DataFrame()

for column in features:
    mean = X[column].mean()
    std = X[column].std(ddof=0)

    z_score[column] = (
        (X[column] - mean) / std
    )

z_score = pd.concat(
    [df[['Student ID']], z_score],
    axis=1
)

z_score.round(3)

  Student ID    Age  Attendance (%)  Study Hours/Week  Marks
0        S01 -1.507          -1.588            -1.325 -1.417
1        S02 -0.949          -1.115            -0.918 -1.074
2        S03 -0.391          -0.643            -0.714 -0.674
3        S04  0.167          -0.170            -0.306 -0.389
4        S05 -0.949           0.302             0.102  0.069
5        S06  0.726           0.775             0.510  0.468
6        S07 -0.391          -0.926            -1.122 -0.846
7        S08  1.284           0.586             0.714  0.868
8        S09  0.167           1.248             1.325  1.325
9        S10  1.842           1.531             1.733  1.668

### **Decimal Scaling**

In [7]:
decimal_scaled = pd.DataFrame()

decimal_j = {}

for column in features:
    max_abs = X[column].abs().max()

    j = len(str(int(max_abs)))

    decimal_j[column] = j

    decimal_scaled[column] = X[column] / (10 ** j)

decimal_scaled = pd.concat(
    [df[['Student ID']], decimal_scaled],
    axis=1
)

print("Values of j:")
print(decimal_j)

print("\nDecimal Scaling Result:")
decimal_scaled.round(3)

Values of j:
{'Age': 2, 'Attendance (%)': 2, 'Study Hours/Week': 2, 'Marks': 2}

Decimal Scaling Result:

  Student ID   Age  Attendance (%)  Study Hours/Week  Marks
0        S01  0.18            0.65              0.05   0.42
1        S02  0.19            0.70              0.07   0.48
2        S03  0.20            0.75              0.08   0.55
3        S04  0.21            0.80              0.10   0.60
4        S05  0.19            0.85              0.12   0.68
5        S06  0.22            0.90              0.14   0.75
6        S07  0.20            0.72              0.06   0.52
7        S08  0.23            0.88              0.15   0.82
8        S09  0.21            0.95              0.18   0.90
9        S10  0.24            0.98              0.20   0.96

### **Mean Normalisation**

In [8]:
mean_normalized = pd.DataFrame()

for column in features:
    mean = X[column].mean()
    min_val = X[column].min()
    max_val = X[column].max()

    mean_normalized[column] = (
        (X[column] - mean) /
        (max_val - min_val)
    )

mean_normalized = pd.concat(
    [df[['Student ID']], mean_normalized],
    axis=1
)

mean_normalized.round(3)

  Student ID    Age  Attendance (%)  Study Hours/Week  Marks
0        S01 -0.450          -0.509            -0.433 -0.459
1        S02 -0.283          -0.358            -0.300 -0.348
2        S03 -0.117          -0.206            -0.233 -0.219
3        S04  0.050          -0.055            -0.100 -0.126
4        S05 -0.283           0.097             0.033  0.022
5        S06  0.217           0.248             0.167  0.152
6        S07 -0.117          -0.297            -0.367 -0.274
7        S08  0.383           0.188             0.233  0.281
8        S09  0.050           0.400             0.433  0.430
9        S10  0.550           0.491             0.567  0.541

### **Robust Scaling**

In [9]:
robust_scaled = pd.DataFrame()

for column in features:
    median = X[column].median()

    Q1 = X[column].quantile(0.25)
    Q3 = X[column].quantile(0.75)

    IQR = Q3 - Q1

    robust_scaled[column] = (
        (X[column] - median) / IQR
    )

robust_scaled = pd.concat(
    [df[['Student ID']], robust_scaled],
    axis=1
)

robust_scaled.round(3)

  Student ID  Age  Attendance (%)  Study Hours/Week  Marks
0        S01 -1.0          -1.045            -0.800 -0.800
1        S02 -0.6          -0.746            -0.533 -0.582
2        S03 -0.2          -0.448            -0.400 -0.327
3        S04  0.2          -0.149            -0.133 -0.145
4        S05 -0.6           0.149             0.133  0.145
5        S06  0.6           0.448             0.400  0.400
6        S07 -0.2          -0.627            -0.667 -0.436
7        S08  1.0           0.328             0.533  0.655
8        S09  0.2           0.746             0.933  0.945
9        S10  1.4           0.925             1.200  1.164

In [10]:
print("ORIGINAL DATASET")
display(df)

print("MIN-MAX NORMALIZATION")
display(min_max.round(3))

print("Z-SCORE NORMALIZATION")
display(z_score.round(3))

print("DECIMAL SCALING")
display(decimal_scaled.round(3))

print("MEAN NORMALIZATION")
display(mean_normalized.round(3))

print("ROBUST SCALING")
display(robust_scaled.round(3))

ORIGINAL DATASET

  Student ID  Age  Attendance (%)  Study Hours/Week  Marks
0        S01   18              65                 5     42
1        S02   19              70                 7     48
2        S03   20              75                 8     55
3        S04   21              80                10     60
4        S05   19              85                12     68
5        S06   22              90                14     75
6        S07   20              72                 6     52
7        S08   23              88                15     82
8        S09   21              95                18     90
9        S10   24              98                20     96

MIN-MAX NORMALIZATION

  Student ID    Age  Attendance (%)  Study Hours/Week  Marks
0        S01  0.000           0.000             0.000  0.000
1        S02  0.167           0.152             0.133  0.111
2        S03  0.333           0.303             0.200  0.241
3        S04  0.500           0.455             0.333  0.333
4        S05  0.167           0.606             0.467  0.481
5        S06  0.667           0.758             0.600  0.611
6        S07  0.333           0.212             0.067  0.185
7        S08  0.833           0.697             0.667  0.741
8        S09  0.500           0.909             0.867  0.889
9        S10  1.000           1.000             1.000  1.000

Z-SCORE NORMALIZATION

  Student ID    Age  Attendance (%)  Study Hours/Week  Marks
0        S01 -1.507          -1.588            -1.325 -1.417
1        S02 -0.949          -1.115            -0.918 -1.074
2        S03 -0.391          -0.643            -0.714 -0.674
3        S04  0.167          -0.170            -0.306 -0.389
4        S05 -0.949           0.302             0.102  0.069
5        S06  0.726           0.775             0.510  0.468
6        S07 -0.391          -0.926            -1.122 -0.846
7        S08  1.284           0.586             0.714  0.868
8        S09  0.167           1.248             1.325  1.325
9        S10  1.842           1.531             1.733  1.668

DECIMAL SCALING

  Student ID   Age  Attendance (%)  Study Hours/Week  Marks
0        S01  0.18            0.65              0.05   0.42
1        S02  0.19            0.70              0.07   0.48
2        S03  0.20            0.75              0.08   0.55
3        S04  0.21            0.80              0.10   0.60
4        S05  0.19            0.85              0.12   0.68
5        S06  0.22            0.90              0.14   0.75
6        S07  0.20            0.72              0.06   0.52
7        S08  0.23            0.88              0.15   0.82
8        S09  0.21            0.95              0.18   0.90
9        S10  0.24            0.98              0.20   0.96

MEAN NORMALIZATION

  Student ID    Age  Attendance (%)  Study Hours/Week  Marks
0        S01 -0.450          -0.509            -0.433 -0.459
1        S02 -0.283          -0.358            -0.300 -0.348
2        S03 -0.117          -0.206            -0.233 -0.219
3        S04  0.050          -0.055            -0.100 -0.126
4        S05 -0.283           0.097             0.033  0.022
5        S06  0.217           0.248             0.167  0.152
6        S07 -0.117          -0.297            -0.367 -0.274
7        S08  0.383           0.188             0.233  0.281
8        S09  0.050           0.400             0.433  0.430
9        S10  0.550           0.491             0.567  0.541

ROBUST SCALING

  Student ID  Age  Attendance (%)  Study Hours/Week  Marks
0        S01 -1.0          -1.045            -0.800 -0.800
1        S02 -0.6          -0.746            -0.533 -0.582
2        S03 -0.2          -0.448            -0.400 -0.327
3        S04  0.2          -0.149            -0.133 -0.145
4        S05 -0.6           0.149             0.133  0.145
5        S06  0.6           0.448             0.400  0.400
6        S07 -0.2          -0.627            -0.667 -0.436
7        S08  1.0           0.328             0.533  0.655
8        S09  0.2           0.746             0.933  0.945
9        S10  1.4           0.925             1.200  1.164

In [11]:
print("Min-Max range:")
print(min_max[features].min().round(3))
print(min_max[features].max().round(3))

print("\nZ-Score mean:")
print(z_score[features].mean().round(3))

print("\nZ-Score population standard deviation:")
print(z_score[features].std(ddof=0).round(3))

Min-Max range:
Age                 0.0
Attendance (%)      0.0
Study Hours/Week    0.0
Marks               0.0
dtype: float64
Age                 1.0
Attendance (%)      1.0
Study Hours/Week    1.0
Marks               1.0
dtype: float64

Z-Score mean:
Age                 0.0
Attendance (%)      0.0
Study Hours/Week    0.0
Marks               0.0
dtype: float64

Z-Score population standard deviation:
Age                 1.0
Attendance (%)      1.0
Study Hours/Week    1.0
Marks               1.0
dtype: float64

# **Analysis**

**Q1. What is normalization and why is it required?**

Answer:
Normalization is a data preprocessing technique used to transform numerical features to comparable scales. It is required because features with larger numerical values may otherwise dominate calculations or machine-learning models.

**Q2. What is the difference between normalization and standardization?**

Answer:
Normalization generally transforms data to a specified range, such as 0 to 1. Standardization transforms data based on its mean and standard deviation, generally producing mean 0 and standard deviation 1.

**Q3. Why are Student ID values not normalized?**

Answer:
Student ID is an identifier, not a meaningful numerical feature. Mathematical operations on it do not represent any useful relationship between students.

**Q4. What does a negative Z-score indicate?**

Answer:
A negative Z-score indicates that the value is below the mean.

**Q5. Why does Z-score normalization not restrict values to the range 0 to 1?**

Answer:
Z-score normalization measures how far a value is from the mean in terms of standard deviations. Therefore, its values can be negative or greater than 1.

**Q6. Which normalization method is most appropriate when outliers are present?**

Answer:
Robust Scaling is most appropriate because it uses the median and interquartile range, which are less affected by extreme values.

**Q7. What is the role of the interquartile range in Robust Scaling?**

Answer:
The IQR, calculated as \(Q_3-Q_1\), measures the spread of the middle 50% of the data and provides a robust scaling factor that is less affected by outliers.

**Q8. What is the difference between population and sample standard deviation?**

Answer:
Population standard deviation describes the variability of the entire population and uses \(N\) in the denominator. Sample standard deviation estimates population variability from a sample and uses \(N-1\).

**Q9. Does normalization change the order of the original values? Explain.**

Answer:
For the normalization methods used here, the transformations are monotonic, so the relative order of values is preserved. A larger original value remains larger after transformation.

**Q10. Why should a scaler normally be fitted only on training data?**

Answer:
The scaler should be fitted only on training data to prevent information from the test set from influencing the preprocessing parameters. This prevents data leakage and gives a more reliable evaluation of the machine-learning model.